# Code by OGResearch
"""
Save and load an irispie model through the ogi HDF5 model file.

This is what the ogi infrastructure does between the `rm` action and every
action that uses the model (`sm`, `fo`, ...), copied here without the ogi
package so the folder stands alone. Sources, all under
modules/codes/python/general/converters/:

    save_model.py, extract_properties.py, save_attributes.py,
    save_dict_to_h5.py, string_to_bytes.py, check_numeric_scalars.py
    load_model.py, load_attributes.py, load_dict_from_h5.py, bytes_to_string.py

The design, and what it means for timing
----------------------------------------
`<mc>_model.h5` does NOT hold a solved model object. It holds two groups:

    model          the model SOURCE, re-generated from the parsed object
                   (declarations with descriptions, equations, log status)
    properties     parameters, stds and -- for a nonlinear model -- the
                   steady levels and steady changes of every quantity

MATLAB's `rm` saves the solved object (`gpm_model.mat`) and the next action
just loads it. In Python every consumer REBUILDS the model from this file:
parse the source again, assign the parameters, and re-solve. The steady
state is not re-derived when the saved one still satisfies the equations
(`check_steady` first); otherwise `steady()` runs again from the saved
values as its starting guess. That is the "steady guess" of read_model.py,
and the h5 is where it comes from.

Why not pickle the solved object? It would work inside ogi (the context
functions it refers to are importable there), but the h5 is readable by
MATLAB and without irispie, and a pickle is tied to the irispie version that
wrote it. Both are design choices of the ogi infrastructure, not technical
limits, and could be extended.

Differences from the ogi source: the `platform="matlab"` output and the
older-irispie shock headers are dropped (irispie-pe 0.79.6 uses `!shocks`),
and `save_to_h5` is inlined. Everything else is verbatim in behaviour.
"""

from typing import Any

import h5py as h5
import irispie as ir
import numpy as np


# ================================================================== saving
def save_model(m: ir.Simultaneous, output_h5_file: str) -> None:
    """Write the model source and properties to `output_h5_file`."""

    headers = {
        "y_variables": "!measurement-variables",
        "x_variables": "!transition-variables",
        "log_variables": "!log-variables",
        "y_shocks": "!measurement-shocks",
        "xu_shocks": "!shocks",
        "parameters": "!parameters",
        "y_equations": "!measurement-equations",
        "x_equations": "!transition-equations",
    }
    body: dict = {key: [] for key in headers}
    body["stds"] = []

    for quantity in m.get_quantities():
        text = f"\"{quantity.description}\" {quantity.human}"
        if quantity.kind in ir.MEASUREMENT_VARIABLE:
            body["y_variables"].append(text)
        elif quantity.kind in ir.TRANSITION_VARIABLE:
            body["x_variables"].append(text)
        elif quantity.kind in ir.MEASUREMENT_SHOCK:
            body["y_shocks"].append(text)
        elif quantity.kind in ir.TRANSITION_SHOCK:
            # anticipated twins are generated by the parser, so not declared
            if not quantity.human.startswith("ant_shock_"):
                body["xu_shocks"].append(text)
        elif quantity.kind in ir.PARAMETER:
            body["parameters"].append(text)
        elif quantity.kind in (ir.MEASUREMENT_STD | ir.TRANSITION_STD):
            if not quantity.human.startswith("std_ant_shock_"):
                body["stds"].append(text)

    for key, value in m.get_log_status().items():
        if value:
            body["log_variables"].append(key)

    for equation in m.get_dynamic_equation_objects():
        text = f"\"{equation.description}\" {equation.human}"
        if equation.kind in ir.MEASUREMENT_EQUATION:
            body["y_equations"].append(text)
        elif equation.kind in ir.TRANSITION_EQUATION:
            body["x_equations"].append(text)

    model = "# model source file extracted from an irispie Model object\n"
    for key, header in headers.items():
        model += f"\n{header}\n"
        terminator = ";" if header.endswith("-equations") else ""
        for item in body[key]:
            model += f"{item}{terminator}\n"

    output = {"model": model, "properties": extract_properties(m)}
    with h5.File(output_h5_file, "w") as file:
        for key, value in output.items():
            _save_dict_to_h5(file, value, key)


def extract_properties(m: ir.Simultaneous) -> dict:
    """Parameters, stds and (nonlinear only) the steady state."""

    properties = {
        "parameters": m.get_parameters(),
        "stds": m.get_stds(),
    }
    # A linear model reads its steady state off the solution; a nonlinear
    # one cannot reliably re-derive it (near-unit-root trends), so the one it
    # was solved with travels along as the next solver's starting point.
    if not m.is_linear:
        properties["steady_levels"] = _finite_only(m.get_steady_levels())
        properties["steady_changes"] = _finite_only(m.get_steady_changes())
    return properties


def _finite_only(values: dict) -> dict:
    kept = {}
    for name, value in values.items():
        array = np.asarray(value, dtype=float)
        if array.size and np.all(np.isfinite(array)):
            kept[name] = value
    return kept


def _save_dict_to_h5(group: h5.Group, value: Any, name: str) -> None:
    """Recursively write a dict as groups and datasets."""

    if isinstance(value, dict):
        sub = group.create_group(name)
        for key, item in value.items():
            _save_dict_to_h5(sub, item, key)
        return
    group.create_dataset(name, data=_string_to_bytes(_check_numeric_scalars(value)))


def _check_numeric_scalars(value: Any) -> Any:
    """Wrap scalars into (1, 1) matrices so that every dataset has a shape."""

    if isinstance(value, (bool, np.bool_)):
        return np.full((1, 1), value, dtype=bool)
    if np.isscalar(value) and np.issubdtype(type(value), np.number):
        return np.full((1, 1), value, dtype=float)
    return value


def _string_to_bytes(value: Any) -> Any:
    """A string becomes a (1, N) matrix of single bytes, MATLAB-readable."""

    if not isinstance(value, str):
        return value
    if len(value) == 0:
        return np.empty((1, 0), dtype="S1")
    return np.array([list(bytes(char, "utf-8") for char in value)])


# ================================================================= loading
def load_model(
    input_h5_file: str,
    context: dict,
    linear: bool = False,
    sstol: float = 1e-10,
    solvetol: float = 1e-10,
) -> ir.Simultaneous:
    """
    Rebuild a solved model from the h5: parse, assign, steady, solve.

    `context` carries the functions the equations call (erf, smax0_, ...),
    which the h5 cannot store -- they come from utils.model_functions.
    """

    with h5.File(input_h5_file, "r") as file:
        model = _load_dict_from_h5(file, "model")
        properties = _load_dict_from_h5(file, "properties")

    m = ir.Simultaneous.from_string(model, linear=linear, context=context)
    m.assign(properties["parameters"] | properties["stds"])

    # seed the steady state with the one the model was saved with
    guess = steady_state_guess(properties)
    m.assign(guess)

    if linear:
        m.solve(tolerance=solvetol)
        m.steady()
    else:
        # the saved steady state is not re-derived when it still satisfies
        # the equations -- re-solving a near-unit-root level can only move it
        if not (guess and m.check_steady(when_fails="silent", tolerance=sstol)):
            m.steady()
        m.solve(tolerance=solvetol)

    m.check_steady(when_fails="error", tolerance=sstol)
    return m


def steady_state_guess(properties: dict) -> dict:
    """{name: level} or {name: (level, change)}, as `assign` takes it."""

    levels = properties.get("steady_levels", {})
    changes = properties.get("steady_changes", {})
    guess = {}
    for name, level in levels.items():
        level = float(np.asarray(level).flatten()[0])
        if name in changes:
            guess[name] = (level, float(np.asarray(changes[name]).flatten()[0]))
        else:
            guess[name] = level
    return guess


def _load_dict_from_h5(group: h5.Group, name: str) -> Any:
    """Recursively read groups into dicts and datasets into values."""

    node = group[name]
    if isinstance(node, h5.Dataset):
        return _decode_dataset(node)
    return {key: _load_dict_from_h5(node, key) for key in node.keys()}


def _decode_dataset(dataset: h5.Dataset) -> Any:
    raw = dataset[()]
    if dataset.shape == ():
        return raw.decode("utf-8") if isinstance(raw, bytes) else (
            raw.item() if isinstance(raw, np.generic) else raw)
    if isinstance(raw, np.ndarray):
        if raw.ndim == 2 and raw.shape[1] == 1:
            raw = raw[:, 0]
        elif raw.ndim == 2 and raw.shape[0] == 1:
            raw = raw[0]
        if raw.dtype.kind == "b":
            return bool(raw.flatten()[0]) if raw.size == 1 else raw
    return _bytes_to_string(raw)


def _bytes_to_string(array: Any) -> Any:
    if not all(isinstance(byte, bytes) for byte in array):
        return array
    try:
        return "".join(byte.decode("utf-8") for byte in array)
    except UnicodeDecodeError:
        return "".join(byte.decode("latin-1") for byte in array)
