name: Upload new release to PYPI


on:
  workflow_dispatch:


jobs:
  deploy:
    name: Create and upload dist to PYPI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build and twine
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

      - name: Checkout master
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: master
          path: .

      - name: Build dist files
        run: |
          python -m build
    
      - name: Upload
        run: |
          python -m twine upload -r pypi -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
  
      
    
