name: Upload new release to PYPI


on:
  workflow_dispatch:


jobs:
  deploy:
    name: Create and upload dist to PYPI
    runs-on: ubuntu-latest
    steps:
      - name: Capture version from pyproject.toml
        id: captureversion
        run: |
          echo "version=${grep -m 1 -o version | tr -d '[a-z=" ]'}" >> "$GITHUB_OUTPUT"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build and twine
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

      - name: Checkout master
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: master
          path: .

      - name: Build dist files
        run: |
          echo "Building version ${{ steps.captureversion.version }}"
          python -m build
    
      - name: Upload
        run: |
          python -m twine upload dist/* -r pypi -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
          
      - name: Create artifacts
        uses: actions/upload-artifact@master
        with: 
          name: dist-${{ steps.captureversion.version }}
          path: dist/*
