name: Upload new release to PYPI


on:
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  deploy:
    name: Create and upload dist to PYPI
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build and twine
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

      - name: Checkout master
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: master
          path: .

      - name: Capture version from pyproject.toml
        id: capture-version
        run: |
          grep -m 1 version pyproject.toml
          grep -m 1 version pyproject.toml | tr -d '[a-z=" ]'
          version=$(grep -m 1 version pyproject.toml | tr -d '[a-z=" ]')
          echo $version
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Build dist files
        run: |
          echo "Building version ${{ steps.capture-version.outputs.version }}"
          python -m build

      - name: Upload
        run: |
          python -m twine upload dist/* -r pypi -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

      - name: Create artifacts
        uses: actions/upload-artifact@master
        with:
          name: dist-${{ steps.capture-version.outputs.version }}
          path: dist/*

