name: Sync from irispie repository

on:
  repository_dispatch:
    types: [new-version]

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout irispie-re repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Backup LICENSE file
      run: |
        if [ -f LICENSE ]; then
          cp LICENSE LICENSE.backup
        fi
    
    - name: Add irispie remote with authentication
      run: |
        git remote add irispie https://${{ secrets.IRISPIE_PAT }}@github.com/OWNER/irispie.git || \
        git remote set-url irispie https://${{ secrets.IRISPIE_PAT }}@github.com/OWNER/irispie.git
      env:
        IRISPIE_PAT: ${{ secrets.IRISPIE_PAT }}
    
    - name: Fetch from irispie
      run: |
        git fetch irispie master
    
    - name: Merge changes from irispie
      run: |
        git merge irispie/master --allow-unrelated-histories -m "Sync from irispie repository (new-version event)"
    
    - name: Restore LICENSE file
      run: |
        if [ -f LICENSE.backup ]; then
          mv LICENSE.backup LICENSE
          git add LICENSE
          git commit -m "Preserve irispie-re LICENSE file" || true
        fi
    
    - name: Push changes
      run: |
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Clean up remote
      run: |
        git remote remove irispie || true