on:
  workflow_dispatch:
    
jobs:
  test:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
          path: ./irispie-package
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: IRIS-Solutions-Team/irispie

      - name: When passed
        run: |
          cd $GITHUB_WORKSPACE/irispie-package
          ls -al
          echo "${{ secrets.IRISPIE_SERVICE_TOKEN }}"
          git config --local user.email "jaromir.benes@gmail.com"
          git config --local user.name "Jaromir Benes"
          git remote set-url origin  https://github.com/IRIS-Solutions-Team/irispie.git
          echo "XXX" > xxx
          cat .git/config
          # git switch -c push_test
          git add xxx
          git commit -m Test
          git push

on:
  workflow_dispatch:
    
jobs:
  test:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
          path: ./irispie-package
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: IRIS-Solutions-Team/irispie

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -e ./irispie-package
          pip install pytest

<<<<<<< HEAD
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/irispie-package
          pytest ./tests/series -ra > ./tests/report.txt

      - name: Bump version
        if: ${{ success() }}
        run: |
          if ! [[ -e .bump_type ]]; then
            echo "Cannot release without .bump_type"
            exit 1
          fi
          BUMP_TYPE=$(< .bump_type)
          python ./irispie-package/scripts/bump_version.py \
            --bump_type=$BUMP_TYPE \
            --source_path=./irispie-package/pyproject.toml
>>>>>>> 4e64e8c (Update test.yml)

      - name: When passed
        if: ${{ success() }}
        run: |
          cd $GITHUB_WORKSPACE/irispie-package
          ls -al
          echo "${{ secrets.IRISPIE_SERVICE_TOKEN }}"
          git config --local user.email "jaromir.benes@gmail.com"
          git config --local user.name "Jaromir Benes"
          if [[ $(git ls-remote --heads origin */test) ]]; then
            git push origin --delete test
          fi
          git switch -c test
          git add ./irispie-package/tests/report.txt
          git commit -m Test
          git push origin test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Test results
          path: ./irispie-package/tests/report.txt

