on:
  workflow_dispatch:
    
jobs:
  test:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: master
          path: ./irispie-package
          token: ${{ secrets.IRISPIE_SERVICE_TOKEN }}
          persist-credentials: false

      - name: Configure user name
        run: |
          cd $GITHUB_WORKSPACE/irispie-package
          git config --global user.email "jaromir.benes@gmail.com"
          git config --global user.name "Jaromir Benes"

      - name: When passed
        if: ${{ success() }}
        run: |
          cd $GITHUB_WORKSPACE/irispie-package
          echo "XXX" > ./irispie-package/xxx
          cd ./irispie-package
          cat .git/config
          git switch -c push_test
          git add xxx
          git commit -m Test
          git push origin push_test

      - name: When failed
        if: ${{ failure() }}
        run: |
          echo Failed
