on:
  workflow_dispatch:
    
jobs:
  test:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
          path: ./irispie-package
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: IRIS-Solutions-Team/irispie

      - name: When passed
        run: |
          cd $GITHUB_WORKSPACE/irispie-package
          ls -al
          echo "${{ secrets.IRISPIE_SERVICE_TOKEN }}"
          git config --local user.email "jaromir.benes@gmail.com"
          git config --local user.name "Jaromir Benes"
          echo "XXX" > xxx
          cat .git/config
          # git switch -c push_test
          git add xxx
          git commit -m Test
          git push

