on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Abcd
        options:
          - aaa
          - bbb
          - ccc
      another:
        type: string
        default: $(echo "a")
        required: true
    
jobs:
  test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/setup-python@v4
         with:
           python-version: "3.11"
       - run: |
           pip install irispie
           python -c "import numpy as np; print(np.zeros((3,3)))"
