on:
  workflow_dispatch:
    
jobs:
  test:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
          path: ./irispie-package
          token: ${{ secrets.IRISPIE_CONTENTS_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          pip install -e ./irispie-package
          pip install pytest

      - run: |
          cd $GITHUB_WORKSPACE/irispie-package
          pytest ./tests/series -ra > ./tests/report.txt

      - name: When passed
        if: ${{ success() }}
        run: |
          cd $GITHUB_WORKSPACE/irispie-package
          ls -al
          echo "${{ secrets.IRISPIE_SERVICE_TOKEN }}"
          git config --local user.email "jaromir.benes@gmail.com"
          git config --local user.name "Jaromir Benes"
          if [[ $(git ls-remote --heads github */test) ]]; then
            git push origin --delete test
          fi
          git switch -c test
          git add ./tests/report.txt          
          git commit -m Test
          git push origin test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Test results
          path: ./irispie-package/tests/report.txt

